# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170220_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '\u6388\u8bfe\u6559\u5e08', 'verbose_name_plural': '\u6388\u8bfe\u6559\u5e08'},
        ),
    ]
