# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170222_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y/%m', verbose_name='\u6559\u5e08\u56fe'),
        ),
    ]
